apiVersion: apps.kommander.d2iq.io/v1alpha3
kind: AppDeployment
metadata:
  name: istio-helm
  namespace: kommander-default-workspace
spec:
  appRef:
    kind: ClusterApp
    name: istio-helm-1.23.6
  clusterConfigOverrides:
    - appVersion: 1.23.6
      clusterSelector:
        matchExpressions:
          - key: kommander.d2iq.io/cluster-name
            operator: In
            values:
              - workload01
      configMapName: ''
    - appVersion: 1.23.6
      clusterSelector:
        matchExpressions:
          - key: kommander.d2iq.io/cluster-name
            operator: In
            values:
              - workload02
      configMapName: ''
  clusterSelector:
    matchExpressions:
      - key: kommander.d2iq.io/cluster-name
        operator: In
        values:
          - workload01
          - workload02
